/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estadistica;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author DAGonzalezH
 */
public class Estadistica extends javax.swing.JFrame {

    /**
     * Creates new form Estadistica
     */
     Lista lista=new Lista();
    JList lista2= new JList();
    DefaultListModel modelo= new DefaultListModel();
 
    public Estadistica() {
        initComponents();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnmedia = new javax.swing.JButton();
        btncalcularmediana = new javax.swing.JButton();
        btnmoda = new javax.swing.JButton();
        btnvarianza = new javax.swing.JButton();
        btndesviacion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtmen = new javax.swing.JTextField();
        txtmay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Realizar Cálculos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 140, 30));

        jLabel2.setText("Números");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 49, 72, 21));
        getContentPane().add(txtnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 49, 61, -1));

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 88, -1, -1));

        jLabel3.setText("Lista ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 100, -1));

        btnmedia.setText("Calcular Media");
        btnmedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmediaActionPerformed(evt);
            }
        });
        getContentPane().add(btnmedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        btncalcularmediana.setText("Calcular Mediana");
        btncalcularmediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularmedianaActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcularmediana, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        btnmoda.setText("Calcular Moda");
        btnmoda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodaActionPerformed(evt);
            }
        });
        getContentPane().add(btnmoda, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        btnvarianza.setText("Calcular Varianza");
        btnvarianza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvarianzaActionPerformed(evt);
            }
        });
        getContentPane().add(btnvarianza, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        btndesviacion.setText("Calcular Desviación Estándar");
        btndesviacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndesviacionActionPerformed(evt);
            }
        });
        getContentPane().add(btndesviacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, -1, -1));

        jLabel4.setText("Número Mayor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 126, -1, -1));

        jLabel5.setText("Número Menor");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 161, -1, -1));
        getContentPane().add(txtmen, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 30));

        txtmay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmayActionPerformed(evt);
            }
        });
        getContentPane().add(txtmay, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 123, 120, 30));

        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmayActionPerformed
      
        
    }//GEN-LAST:event_txtmayActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        modelo.clear();
        
        int num=Integer.parseInt(txtnum.getText());
        lista.agregaralfinal(num);
        String salida="";
        Nodo aux=lista.getInicio();
        lista.listaordenada(lista);
              while(aux!=null){
                  
                  modelo.addElement(aux.getDato());
                  salida=salida+aux.getDato()+"->";
                  aux=aux.getSig();
                }
         System.out.println(salida+"null");     
         jList1.setModel(modelo);
          Nodo aux2=lista.getInicio();
          txtmay.setText(""+lista.numeromayor());
          txtmen.setText(""+aux2.getDato());
         
    
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnmediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmediaActionPerformed
        
        lista.calcularpromedio();
        
        
        
    }//GEN-LAST:event_btnmediaActionPerformed

    private void btncalcularmedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularmedianaActionPerformed
        
        JOptionPane.showMessageDialog(null,lista.calcularmediana(),"informacion",JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btncalcularmedianaActionPerformed

    private void btnvarianzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvarianzaActionPerformed
        
        JOptionPane.showMessageDialog(null,lista.calcularvarianza(),"Información",JOptionPane.INFORMATION_MESSAGE);
        
        
    }//GEN-LAST:event_btnvarianzaActionPerformed

    private void btndesviacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndesviacionActionPerformed
    
        lista.calculardesviacion();
        
        
    }//GEN-LAST:event_btndesviacionActionPerformed

    private void btnmodaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodaActionPerformed

        lista.calcularmoda();
    }//GEN-LAST:event_btnmodaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadistica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcularmediana;
    private javax.swing.JButton btndesviacion;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnmedia;
    private javax.swing.JButton btnmoda;
    private javax.swing.JButton btnvarianza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList jList1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtmay;
    private javax.swing.JTextField txtmen;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
