/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorala;

import com.sun.corba.se.impl.naming.cosnaming.InterOperableNamingImpl;
import java.awt.Toolkit;
import java.util.Enumeration;
import java.util.Hashtable;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Agregarmarcador extends javax.swing.JDialog {

     Hashtable<String, Partido> tabla_partido = new Hashtable<String, Partido> ();
    /**
     * Creates new form Agregarmarcador
     */
    public Agregarmarcador(java.awt.Frame parent, boolean modal, Hashtable<String, Partido> tabla_partido) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.tabla_partido=tabla_partido;
    }

    private Agregarmarcador(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txttitulo = new javax.swing.JLabel();
        txtnombrelocal = new javax.swing.JTextField();
        txtgoleslocal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblnombreequipolocal = new javax.swing.JLabel();
        lblgoleslocal = new javax.swing.JLabel();
        lblnombrevisitante = new javax.swing.JLabel();
        txtnombrevisitante = new javax.swing.JTextField();
        lblgolesvisitantes = new javax.swing.JLabel();
        txtgolesvisitantes = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txttitulo.setText("AGREGAR MARCADOR ");

        txtnombrelocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrelocalActionPerformed(evt);
            }
        });
        txtnombrelocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrelocalKeyTyped(evt);
            }
        });

        txtgoleslocal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgoleslocalKeyTyped(evt);
            }
        });

        lblnombreequipolocal.setText("Nombre Equipo Local :*");

        lblgoleslocal.setText("Goles Marcados :*");

        lblnombrevisitante.setText("Nombre Equipo Visitante :* ");

        txtnombrevisitante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombrevisitanteKeyTyped(evt);
            }
        });

        lblgolesvisitantes.setText("Goles Marcados :*");

        txtgolesvisitantes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtgolesvisitantesKeyTyped(evt);
            }
        });

        btnguardar.setText("GUARDAR ");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnlimpiar.setText("LIMPIAR ");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombrevisitante)
                            .addComponent(lblgoleslocal)
                            .addComponent(lblnombreequipolocal)
                            .addComponent(lblgolesvisitantes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnombrelocal)
                            .addComponent(txtgoleslocal)
                            .addComponent(txtnombrevisitante)
                            .addComponent(txtgolesvisitantes, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(btnguardar)
                .addGap(57, 57, 57)
                .addComponent(btnlimpiar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txttitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombrelocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombreequipolocal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtgoleslocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblgoleslocal))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombrevisitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblnombrevisitante))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblgolesvisitantes)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addComponent(txtgolesvisitantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnguardar)
                    .addComponent(btnlimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombrelocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrelocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrelocalActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        
      if(!txtnombrevisitante.getText().equals("")&&!txtgolesvisitantes.equals("") && txtnombrelocal.getText().equals("")&& txtgoleslocal.getText().equals(""))  
      {
      String nombrelocal=txtnombrelocal.getText();
      int goleslocal=Integer.parseInt(txtgoleslocal.getText());
      String nombrevisitante=txtnombrevisitante.getText();
      int golesvisitante=Integer.parseInt(txtgolesvisitantes.getText());
      
      
       String idpartido=asignarllaves(); 
       Partido mipartido= new Partido(nombrelocal, nombrevisitante, goleslocal, golesvisitante);
      tabla_partido.put(idpartido, mipartido);
          btnlimpiarActionPerformed(evt);
      
      JOptionPane.showMessageDialog(null, "El Marcador se ha agregado con éxito", "Exito!", JOptionPane.INFORMATION_MESSAGE);
      
      }
      else{
      JOptionPane.showMessageDialog(null, "Los Campos con * son Obligatorios", "Advertencia ", JOptionPane.WARNING_MESSAGE);    
          
      }
       
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO add your handling code here:
        txtnombrelocal.setText("");
        txtgoleslocal.setText("");
        txtnombrevisitante.setText("");
        txtgolesvisitantes.setText("");
                
        
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txtnombrelocalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrelocalKeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() >= 97 && evt.getKeyChar() <= 122 || evt.getKeyChar() >= 65 && evt.getKeyChar() <= 90 || evt.getKeyChar() == 32 || evt.getKeyChar() == 8) {
            
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "El campo solo recibe letras mayúsculas y/o minuscúlas", "Error ", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        
        
        
    }//GEN-LAST:event_txtnombrelocalKeyTyped

    private void txtnombrevisitanteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombrevisitanteKeyTyped
        // TODO add your handling code here:
      if (evt.getKeyChar() >= 97 && evt.getKeyChar() <= 122 || evt.getKeyChar() >= 65 && evt.getKeyChar() <= 90 || evt.getKeyChar() == 32 || evt.getKeyChar() == 8) {
            
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "El campo solo recibe letras mayúsculas y/o minuscúlas", "Error ", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }  
        
        
    }//GEN-LAST:event_txtnombrevisitanteKeyTyped

    private void txtgoleslocalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgoleslocalKeyTyped
        // TODO add your handling code here:
         
        if (evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57 || evt.getKeyChar() == 8) {
            
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "El campo solo recibe números", "Error ", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }        
        
        
    }//GEN-LAST:event_txtgoleslocalKeyTyped

    private void txtgolesvisitantesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgolesvisitantesKeyTyped
        // TODO add your handling code here:
         
        if (evt.getKeyChar() >= 48 && evt.getKeyChar() <= 57 || evt.getKeyChar() == 8) {
            
        } else {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "El campo solo recibe números", "Error ", JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }        
        
        
    }//GEN-LAST:event_txtgolesvisitantesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregarmarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregarmarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregarmarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregarmarcador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    public String asignarllaves(){
        int llave=0;
      Enumeration <String> llaves= tabla_partido.keys();
        while(llaves.hasMoreElements()){
            llave=Integer.parseInt(llaves.nextElement());
            break;
            
        }
        return ""+(llave+1);
        
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblgoleslocal;
    private javax.swing.JLabel lblgolesvisitantes;
    private javax.swing.JLabel lblnombreequipolocal;
    private javax.swing.JLabel lblnombrevisitante;
    private javax.swing.JTextField txtgoleslocal;
    private javax.swing.JTextField txtgolesvisitantes;
    private javax.swing.JTextField txtnombrelocal;
    private javax.swing.JTextField txtnombrevisitante;
    private javax.swing.JLabel txttitulo;
    // End of variables declaration//GEN-END:variables
}
